[package]
name = "spidior"
version = "0.1.0"
authors = ["John Westhoff <johnwesthoff@nyu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
